# Generated by Django 4.2.4 on 2023-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_restaurant_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='not_approved',
            field=models.BooleanField(default=True),
        ),
    ]
