# Generated by Django 4.2.4 on 2023-10-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_restaurant_lat_restaurant_lng_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=38.0316188, max_digits=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=78.51084589999999, max_digits=10),
        ),
    ]
