# Generated by Django 4.2.4 on 2023-11-08 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='admin_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='not_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
