# Generated by Django 4.2.4 on 2023-11-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_restaurant_zip_code_alter_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
