# Generated by Django 4.2.4 on 2023-10-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_restaurant_city_restaurant_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=38.0316188, max_digits=9),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=78.51084589999999, max_digits=9),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='Rice Hall', max_length=100, unique=True),
        ),
    ]
